language: ruby
dist: xenial
bundle_args: "--without deployment"
cache:
  bundler: true
before_install:
- mkdir -p $PWD/travis_phantomjs
- wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
- tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs
- export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
- phantomjs --version
before_script:
- cp config/database.yml.example config/database.yml
- cp config/secrets.yml.example config/secrets.yml
- bundle exec rake db:setup
- bundle exec rake cgap:db:migrate
jobs:
  include:
  - stage: test
    script: bundle exec rake test
    name: Rake Test
  - script: bundle exec rspec
    name: Rspec
  - stage: build
    if: tag IS present
    before_script:
    - cp config/database.yml.example config/database.yml
    - cp config/secrets.yml.example config/secrets.yml
    script: "./compile-build"
    name: Compile Build
    deploy:
      provider: releases
      file: release.tar.gz
      file_glob: true
      skip_cleanup: true
      on:
        tags: true
        repo: sanger/labwhere
      api_key:
        secure: DvDQ91V1q7AP2PjgzsB9G+3erq504LfYLxNWGooMNtf2AVu9+iLgZcBmsXzIHGtzbAIYs4j+m+7K2/VuokqkiZd1OizP4pntY1PywtTiZ66VEMnsm+TBNSKjuJKbeINQmPJwEhEGxIm1AvzbcnzBS+aKSRtuUTSyCXXPNbJW00M=
